const PREFIX = '';

export const REQUEST_USER_CREDENTIAL = `${PREFIX}REQUEST_USER_CREDENTIAL`;
export const RECEIVE_USER_CREDENTIAL = `${PREFIX}RECEIVE_USER_CREDENTIAL`;

export const REQUEST_USER_AUTHORITY_INFO = `${PREFIX}REQUEST_USER_AUTHORITY_INFO`;
export const RECEIVE_USER_AUTHORITY_INFO = `${PREFIX}RECEIVE_USER_AUTHORITY_INFO`;

export const REQUEST_USER_DETAIL = `${PREFIX}REQUEST_USER_DETAIL`;
export const RECEIVE_USER_DETAIL = `${PREFIX}RECEIVE_USER_DETAIL`;

export const REQUEST_ASSET_DETAIL = `${PREFIX}REQUEST_ASSET_DETAIL`;
export const RECEIVE_ASSET_DETAIL = `${PREFIX}RECEIVE_ASSET_DETAIL`;

export const REQUEST_DISTINCT_ASSET_DETAIL = `${PREFIX}REQUEST_DISTINCT_ASSET_DETAIL`;
export const RECEIVE_DISTINCT_ASSET_DETAIL = `${PREFIX}RECEIVE_DISTINCT_ASSET_DETAIL`;

export const REQUEST_LOCATION_DETAIL = `${PREFIX}REQUEST_LOCATION_DETAIL`;
export const RECEIVE_LOCATION_DETAIL = `${PREFIX}RECEIVE_LOCATION_DETAIL`;

export const RECEIVE_AWS_IMAGE = `${PREFIX}RECEIVE_AWS_IMAGE`;
